--liquibase formatted sql
--changeset bishoy:1
CREATE TABLE IF NOT EXISTS FILE_STATE_STORE
(
    FILE_NAME           VARCHAR(100) PRIMARY KEY,
    FILE_PATH           VARCHAR(255),
    FILE_RETENTION_PERIOD_IN_MS INTEGER,
    CREATED_DATE   TIMESTAMP,
    MODIFIED_DATE  TIMESTAMP
);